#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum NamedColor {
  Black,
  White,
  LightGray,
  Gray,
  DarkGray,
  Red,
  DarkRed,
  LightRed,
  Brown,
  DarkBrown,
  LightBrown,
  Orange,
  Yellow,
  Green,
  DarkGreen,
  LightGreen,
  Blue,
  LightBlue,
  DarkBlue,
  Purple,
  Pink,
}

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum Color {
  Transparent,
  Named(NamedColor),
  Hex(RGB<u8>),
}

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum ColorPalette {
  MasterSystem,
  GameBoyColour,
  Amiga,
  Arne,
  Famicom,
  Atari,
  Pastel,
  Ega,
  Amstrad,
  ProteusMellow,
  ProteusRich,
  ProteusNight,
  C64,
  Whitingjp,
}

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct RGB<A> {
  pub r: A,
  pub g: A,
  pub b: A,
}

impl<A> RGB<A> {
  pub fn new(r: A, g: A, b: A) -> RGB<A> {
    RGB { r, g, b }
  }
}

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct RGBA<A> {
  pub rgb: RGB<A>,
  pub a: A,
}

impl<A> RGBA<A> {
  pub fn new(r: A, g: A, b: A, a: A) -> RGBA<A> {
    RGBA {
      rgb: RGB::new(r, g, b),
      a,
    }
  }

  #[inline]
  pub fn r(self) -> A {
    self.rgb.r
  }

  #[inline]
  pub fn g(self) -> A {
    self.rgb.g
  }

  #[inline]
  pub fn b(self) -> A {
    self.rgb.b
  }

  #[inline]
  pub fn a(self) -> A {
    self.a
  }
}

pub fn to_float_color(palette: ColorPalette, color: Color) -> RGBA<f32> {
  fn from_hex(hex: RGB<u8>) -> RGBA<f32> {
    RGBA::new(
      f32::from(hex.r) / 255.0,
      f32::from(hex.g) / 255.0,
      f32::from(hex.b) / 255.0,
      1.0,
    )
  }

  match color {
    Color::Transparent => RGBA::new(0.0, 0.0, 0.0, 0.0),
    Color::Hex(hex) => from_hex(hex),
    Color::Named(named) => {
      let hex = match palette {
        ColorPalette::MasterSystem => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xFF, 0xFF, 0xFF),
          NamedColor::Gray => RGB::new(0x55, 0x55, 0x55),
          NamedColor::DarkGray => RGB::new(0x55, 0x55, 0x00),
          NamedColor::LightGray => RGB::new(0xAA, 0xAA, 0xAA),
          NamedColor::Red => RGB::new(0xFF, 0x00, 0x00),
          NamedColor::DarkRed => RGB::new(0xAA, 0x00, 0x00),
          NamedColor::LightRed => RGB::new(0xFF, 0x55, 0x55),
          NamedColor::Brown => RGB::new(0xAA, 0x55, 0x00),
          NamedColor::DarkBrown => RGB::new(0x55, 0x00, 0x00),
          NamedColor::LightBrown => RGB::new(0xFF, 0xAA, 0x00),
          NamedColor::Orange => RGB::new(0xFF, 0x55, 0x00),
          NamedColor::Yellow => RGB::new(0xFF, 0xFF, 0x55),
          NamedColor::Green => RGB::new(0x55, 0xAA, 0x00),
          NamedColor::DarkGreen => RGB::new(0x00, 0x55, 0x00),
          NamedColor::LightGreen => RGB::new(0xAA, 0xFF, 0x00),
          NamedColor::Blue => RGB::new(0x55, 0x55, 0xAA),
          NamedColor::LightBlue => RGB::new(0xAA, 0xFF, 0xFF),
          NamedColor::DarkBlue => RGB::new(0x00, 0x00, 0x55),
          NamedColor::Purple => RGB::new(0x55, 0x00, 0x55),
          NamedColor::Pink => RGB::new(0xFF, 0xAA, 0xFF),
        },
        ColorPalette::GameBoyColour => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xFF, 0xFF, 0xFF),
          NamedColor::Gray => RGB::new(0x7F, 0x7F, 0x7C),
          NamedColor::DarkGray => RGB::new(0x3E, 0x3E, 0x44),
          NamedColor::LightGray => RGB::new(0xBA, 0xA7, 0xA7),
          NamedColor::Red => RGB::new(0xA7, 0x12, 0x0C),
          NamedColor::DarkRed => RGB::new(0x88, 0x06, 0x06),
          NamedColor::LightRed => RGB::new(0xBA, 0x38, 0x1F),
          NamedColor::Brown => RGB::new(0x57, 0x38, 0x1F),
          NamedColor::DarkBrown => RGB::new(0x3E, 0x25, 0x19),
          NamedColor::LightBrown => RGB::new(0x8E, 0x63, 0x4B),
          NamedColor::Orange => RGB::new(0xBA, 0x4B, 0x32),
          NamedColor::Yellow => RGB::new(0xC0, 0xBA, 0x6F),
          NamedColor::Green => RGB::new(0x51, 0x75, 0x25),
          NamedColor::DarkGreen => RGB::new(0x38, 0x5D, 0x12),
          NamedColor::LightGreen => RGB::new(0x6F, 0x8E, 0x44),
          NamedColor::Blue => RGB::new(0x5D, 0x6F, 0xA7),
          NamedColor::LightBlue => RGB::new(0x8E, 0xA7, 0xA7),
          NamedColor::DarkBlue => RGB::new(0x4B, 0x57, 0x5D),
          NamedColor::Purple => RGB::new(0x3E, 0x3E, 0x44),
          NamedColor::Pink => RGB::new(0xBA, 0x38, 0x1F),
        },
        ColorPalette::Amiga => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xFF, 0xFF, 0xFF),
          NamedColor::Gray => RGB::new(0xBB, 0xBB, 0xBB),
          NamedColor::DarkGray => RGB::new(0x33, 0x33, 0x33),
          NamedColor::LightGray => RGB::new(0xFF, 0xEE, 0xDD),
          NamedColor::Red => RGB::new(0xDD, 0x11, 0x11),
          NamedColor::DarkRed => RGB::new(0x99, 0x00, 0x00),
          NamedColor::LightRed => RGB::new(0xFF, 0x44, 0x22),
          NamedColor::Brown => RGB::new(0x66, 0x33, 0x11),
          NamedColor::DarkBrown => RGB::new(0x33, 0x11, 0x00),
          NamedColor::LightBrown => RGB::new(0xAA, 0x66, 0x44),
          NamedColor::Orange => RGB::new(0xFF, 0x66, 0x44),
          NamedColor::Yellow => RGB::new(0xFF, 0xDD, 0x66),
          NamedColor::Green => RGB::new(0x44, 0x88, 0x11),
          NamedColor::DarkGreen => RGB::new(0x33, 0x55, 0x00),
          NamedColor::LightGreen => RGB::new(0x88, 0xBB, 0x77),
          NamedColor::Blue => RGB::new(0x88, 0x99, 0xDD),
          NamedColor::LightBlue => RGB::new(0xBB, 0xDD, 0xEE),
          NamedColor::DarkBlue => RGB::new(0x66, 0x66, 0x88),
          NamedColor::Purple => RGB::new(0x66, 0x55, 0x55),
          NamedColor::Pink => RGB::new(0x99, 0x77, 0x88),
        },
        ColorPalette::Arne => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xFF, 0xFF, 0xFF),
          NamedColor::Gray => RGB::new(0x9d, 0x9d, 0x9d),
          NamedColor::DarkGray => RGB::new(0x69, 0x71, 0x75),
          NamedColor::LightGray => RGB::new(0xcc, 0xcc, 0xcc),
          NamedColor::Red => RGB::new(0xbe, 0x26, 0x33),
          NamedColor::DarkRed => RGB::new(0x73, 0x29, 0x30),
          NamedColor::LightRed => RGB::new(0xe0, 0x6f, 0x8b),
          NamedColor::Brown => RGB::new(0xa4, 0x64, 0x22),
          NamedColor::DarkBrown => RGB::new(0x49, 0x3c, 0x2b),
          NamedColor::LightBrown => RGB::new(0xee, 0xb6, 0x2f),
          NamedColor::Orange => RGB::new(0xeb, 0x89, 0x31),
          NamedColor::Yellow => RGB::new(0xf7, 0xe2, 0x6b),
          NamedColor::Green => RGB::new(0x44, 0x89, 0x1a),
          NamedColor::DarkGreen => RGB::new(0x2f, 0x48, 0x4e),
          NamedColor::LightGreen => RGB::new(0xa3, 0xce, 0x27),
          NamedColor::Blue => RGB::new(0x1d, 0x57, 0xf7),
          NamedColor::LightBlue => RGB::new(0xB2, 0xDC, 0xEF),
          NamedColor::DarkBlue => RGB::new(0x1B, 0x26, 0x32),
          NamedColor::Purple => RGB::new(0x34, 0x2a, 0x97),
          NamedColor::Pink => RGB::new(0xde, 0x65, 0xe2),
        },
        ColorPalette::Famicom => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xff, 0xff, 0xff),
          NamedColor::Gray => RGB::new(0x7c, 0x7c, 0x7c),
          NamedColor::DarkGray => RGB::new(0x08, 0x08, 0x08),
          NamedColor::LightGray => RGB::new(0xbc, 0xbc, 0xbc),
          NamedColor::Red => RGB::new(0xf8, 0x38, 0x00),
          NamedColor::DarkRed => RGB::new(0x88, 0x14, 0x00),
          NamedColor::LightRed => RGB::new(0xf8, 0x78, 0x58),
          NamedColor::Brown => RGB::new(0xAC, 0x7C, 0x00),
          NamedColor::DarkBrown => RGB::new(0x50, 0x30, 0x00),
          NamedColor::LightBrown => RGB::new(0xFC, 0xE0, 0xA8),
          NamedColor::Orange => RGB::new(0xFC, 0xA0, 0x44),
          NamedColor::Yellow => RGB::new(0xF8, 0xB8, 0x00),
          NamedColor::Green => RGB::new(0x00, 0xB8, 0x00),
          NamedColor::DarkGreen => RGB::new(0x00, 0x58, 0x00),
          NamedColor::LightGreen => RGB::new(0xB8, 0xF8, 0xB8),
          NamedColor::Blue => RGB::new(0x00, 0x58, 0xF8),
          NamedColor::LightBlue => RGB::new(0x3C, 0xBC, 0xFC),
          NamedColor::DarkBlue => RGB::new(0x00, 0x00, 0xBC),
          NamedColor::Purple => RGB::new(0x66, 0x44, 0xFC),
          NamedColor::Pink => RGB::new(0xF8, 0x78, 0xF8),
        },

        ColorPalette::Atari => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xFF, 0xFF, 0xFF),
          NamedColor::Gray => RGB::new(0x90, 0x90, 0x90),
          NamedColor::DarkGray => RGB::new(0x40, 0x40, 0x40),
          NamedColor::LightGray => RGB::new(0xb0, 0xb0, 0xb0),
          NamedColor::Red => RGB::new(0xA0, 0x3C, 0x50),
          NamedColor::DarkRed => RGB::new(0x70, 0x00, 0x14),
          NamedColor::LightRed => RGB::new(0xDC, 0x84, 0x9C),
          NamedColor::Brown => RGB::new(0x80, 0x50, 0x20),
          NamedColor::DarkBrown => RGB::new(0x70, 0x34, 0x00),
          NamedColor::LightBrown => RGB::new(0xCB, 0x98, 0x70),
          NamedColor::Orange => RGB::new(0xCC, 0xAC, 0x70),
          NamedColor::Yellow => RGB::new(0xEC, 0xD0, 0x9C),
          NamedColor::Green => RGB::new(0x58, 0xB0, 0x6C),
          NamedColor::DarkGreen => RGB::new(0x00, 0x64, 0x14),
          NamedColor::LightGreen => RGB::new(0x70, 0xC4, 0x84),
          NamedColor::Blue => RGB::new(0x1C, 0x3C, 0x88),
          NamedColor::LightBlue => RGB::new(0x68, 0x88, 0xC8),
          NamedColor::DarkBlue => RGB::new(0x00, 0x00, 0x88),
          NamedColor::Purple => RGB::new(0x3C, 0x00, 0x80),
          NamedColor::Pink => RGB::new(0xB4, 0x84, 0xDC),
        },
        ColorPalette::Pastel => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xFF, 0xFF, 0xFF),
          NamedColor::Gray => RGB::new(0x3e, 0x3e, 0x3e),
          NamedColor::DarkGray => RGB::new(0x31, 0x31, 0x31),
          NamedColor::LightGray => RGB::new(0x9c, 0xbc, 0xbc),
          NamedColor::Red => RGB::new(0xf5, 0x6c, 0xa2),
          NamedColor::DarkRed => RGB::new(0xa6, 0x35, 0x77),
          NamedColor::LightRed => RGB::new(0xff, 0xa9, 0xcf),
          NamedColor::Brown => RGB::new(0xb5, 0x8c, 0x53),
          NamedColor::DarkBrown => RGB::new(0x78, 0x75, 0x62),
          NamedColor::LightBrown => RGB::new(0xB5, 0x8C, 0x53),
          NamedColor::Orange => RGB::new(0xEB, 0x79, 0x2D),
          NamedColor::Yellow => RGB::new(0xFF, 0xe1, 0x5F),
          NamedColor::Green => RGB::new(0x00, 0xFF, 0x4F),
          NamedColor::DarkGreen => RGB::new(0x2b, 0x73, 0x2c),
          NamedColor::LightGreen => RGB::new(0x97, 0xc0, 0x4f),
          NamedColor::Blue => RGB::new(0x0f, 0x88, 0xd3),
          NamedColor::LightBlue => RGB::new(0x00, 0xff, 0xfe),
          NamedColor::DarkBlue => RGB::new(0x29, 0x3a, 0x7b),
          NamedColor::Purple => RGB::new(0xff, 0x65, 0x54),
          NamedColor::Pink => RGB::new(0xeb, 0x79, 0x2d),
        },
        ColorPalette::Ega => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xff, 0xff, 0xff),
          NamedColor::Gray => RGB::new(0x55, 0x55, 0x55),
          NamedColor::DarkGray => RGB::new(0x55, 0x55, 0x55),
          NamedColor::LightGray => RGB::new(0xaa, 0xaa, 0xaa),
          NamedColor::Red => RGB::new(0xff, 0x55, 0x55),
          NamedColor::DarkRed => RGB::new(0xaa, 0x00, 0x00),
          NamedColor::LightRed => RGB::new(0xff, 0x55, 0xff),
          NamedColor::Brown => RGB::new(0xaa, 0x55, 0x00),
          NamedColor::DarkBrown => RGB::new(0xaa, 0x55, 0x00),
          NamedColor::LightBrown => RGB::new(0xff, 0xff, 0x55),
          NamedColor::Orange => RGB::new(0xff, 0x55, 0x55),
          NamedColor::Yellow => RGB::new(0xff, 0xff, 0x55),
          NamedColor::Green => RGB::new(0x00, 0xaa, 0x00),
          NamedColor::DarkGreen => RGB::new(0x00, 0xaa, 0xaa),
          NamedColor::LightGreen => RGB::new(0x55, 0xff, 0x55),
          NamedColor::Blue => RGB::new(0x55, 0x55, 0xff),
          NamedColor::LightBlue => RGB::new(0x55, 0xff, 0xff),
          NamedColor::DarkBlue => RGB::new(0x00, 0x00, 0xaa),
          NamedColor::Purple => RGB::new(0xaa, 0x00, 0xaa),
          NamedColor::Pink => RGB::new(0xff, 0x55, 0xff),
        },

        ColorPalette::ProteusMellow => match named {
          NamedColor::Black => RGB::new(0x3d, 0x2d, 0x2e),
          NamedColor::White => RGB::new(0xdd, 0xf1, 0xfc),
          NamedColor::Gray => RGB::new(0x9f, 0xb2, 0xd4),
          NamedColor::DarkGray => RGB::new(0x7b, 0x82, 0x72),
          NamedColor::LightGray => RGB::new(0xa4, 0xbf, 0xda),
          NamedColor::Red => RGB::new(0x9d, 0x54, 0x43),
          NamedColor::DarkRed => RGB::new(0x8c, 0x5b, 0x4a),
          NamedColor::LightRed => RGB::new(0x94, 0x61, 0x4c),
          NamedColor::Brown => RGB::new(0x89, 0xa7, 0x8d),
          NamedColor::DarkBrown => RGB::new(0x82, 0x9e, 0x88),
          NamedColor::LightBrown => RGB::new(0xaa, 0xae, 0x97),
          NamedColor::Orange => RGB::new(0xd1, 0xba, 0x86),
          NamedColor::Yellow => RGB::new(0xd6, 0xcd, 0xa2),
          NamedColor::Green => RGB::new(0x75, 0xac, 0x8d),
          NamedColor::DarkGreen => RGB::new(0x8f, 0xa6, 0x7f),
          NamedColor::LightGreen => RGB::new(0x8e, 0xb6, 0x82),
          NamedColor::Blue => RGB::new(0x88, 0xa3, 0xce),
          NamedColor::LightBlue => RGB::new(0xa5, 0xad, 0xb0),
          NamedColor::DarkBlue => RGB::new(0x5c, 0x6b, 0x8c),
          NamedColor::Purple => RGB::new(0xd3, 0x9f, 0xac),
          NamedColor::Pink => RGB::new(0xc8, 0xac, 0x9e),
        },
        ColorPalette::ProteusNight => match named {
          NamedColor::Black => RGB::new(0x01, 0x09, 0x12),
          NamedColor::White => RGB::new(0xfd, 0xee, 0xec),
          NamedColor::Gray => RGB::new(0x05, 0x1d, 0x40),
          NamedColor::DarkGray => RGB::new(0x09, 0x18, 0x42),
          NamedColor::LightGray => RGB::new(0x06, 0x21, 0x51),
          NamedColor::Red => RGB::new(0xad, 0x45, 0x76),
          NamedColor::DarkRed => RGB::new(0x93, 0x47, 0x65),
          NamedColor::LightRed => RGB::new(0xab, 0x62, 0x90),
          NamedColor::Brown => RGB::new(0x61, 0x64, 0x6b),
          NamedColor::DarkBrown => RGB::new(0x3d, 0x2d, 0x2d),
          NamedColor::LightBrown => RGB::new(0x83, 0x93, 0xa0),
          NamedColor::Orange => RGB::new(0x0a, 0x22, 0x27),
          NamedColor::Yellow => RGB::new(0x0a, 0x25, 0x41),
          NamedColor::Green => RGB::new(0x75, 0xac, 0x8d),
          NamedColor::DarkGreen => RGB::new(0x0a, 0x24, 0x34),
          NamedColor::LightGreen => RGB::new(0x06, 0x1f, 0x2e),
          NamedColor::Blue => RGB::new(0x0b, 0x2c, 0x79),
          NamedColor::LightBlue => RGB::new(0x80, 0x9c, 0xcb),
          NamedColor::DarkBlue => RGB::new(0x08, 0x15, 0x3b),
          NamedColor::Purple => RGB::new(0x66, 0x6a, 0x87),
          NamedColor::Pink => RGB::new(0x75, 0x4b, 0x4d),
        },
        ColorPalette::ProteusRich => match named {
          NamedColor::Black => RGB::new(0x6f, 0x68, 0x6f),
          NamedColor::White => RGB::new(0xd1, 0xb1, 0xe2),
          NamedColor::Gray => RGB::new(0xb9, 0xaa, 0xc1),
          NamedColor::DarkGray => RGB::new(0x8e, 0x8b, 0x84),
          NamedColor::LightGray => RGB::new(0xc7, 0xb5, 0xcd),
          NamedColor::Red => RGB::new(0xa1, 0x1f, 0x4f),
          NamedColor::DarkRed => RGB::new(0x93, 0x47, 0x65),
          NamedColor::LightRed => RGB::new(0xc9, 0x98, 0xad),
          NamedColor::Brown => RGB::new(0x89, 0x86, 0x7d),
          NamedColor::DarkBrown => RGB::new(0x79, 0x7f, 0x75),
          NamedColor::LightBrown => RGB::new(0xab, 0x99, 0x97),
          NamedColor::Orange => RGB::new(0xce, 0x8c, 0x5c),
          NamedColor::Yellow => RGB::new(0xf0, 0xd9, 0x59),
          NamedColor::Green => RGB::new(0x75, 0xbc, 0x54),
          NamedColor::DarkGreen => RGB::new(0x59, 0x9d, 0x79),
          NamedColor::LightGreen => RGB::new(0x90, 0xcf, 0x5c),
          NamedColor::Blue => RGB::new(0x8f, 0xd0, 0xec),
          NamedColor::LightBlue => RGB::new(0xbc, 0xdc, 0xe7),
          NamedColor::DarkBlue => RGB::new(0x0b, 0x2c, 0x70),
          NamedColor::Purple => RGB::new(0x9b, 0x37, 0x7f),
          NamedColor::Pink => RGB::new(0xcd, 0x88, 0xe5),
        },
        ColorPalette::Amstrad => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xff, 0xff, 0xff),
          NamedColor::Gray => RGB::new(0x7f, 0x7f, 0x7f),
          NamedColor::DarkGray => RGB::new(0x63, 0x63, 0x63),
          NamedColor::LightGray => RGB::new(0xaf, 0xaf, 0xaf),
          NamedColor::Red => RGB::new(0xff, 0x00, 0x00),
          NamedColor::DarkRed => RGB::new(0x7f, 0x00, 0x00),
          NamedColor::LightRed => RGB::new(0xff, 0x7f, 0x7f),
          NamedColor::Brown => RGB::new(0xff, 0x7f, 0x00),
          NamedColor::DarkBrown => RGB::new(0x7f, 0x7f, 0x00),
          NamedColor::LightBrown => RGB::new(0xff, 0xff, 0x00),
          NamedColor::Orange => RGB::new(0xff, 0x00, 0x7f),
          NamedColor::Yellow => RGB::new(0xff, 0xff, 0x7f),
          NamedColor::Green => RGB::new(0x01, 0xff, 0x00),
          NamedColor::DarkGreen => RGB::new(0x00, 0x7f, 0x00),
          NamedColor::LightGreen => RGB::new(0x7f, 0xff, 0x7f),
          NamedColor::Blue => RGB::new(0x00, 0x00, 0xff),
          NamedColor::LightBlue => RGB::new(0x7f, 0x7f, 0xff),
          NamedColor::DarkBlue => RGB::new(0x00, 0x00, 0x7f),
          NamedColor::Purple => RGB::new(0x7f, 0x00, 0x7f),
          NamedColor::Pink => RGB::new(0xff, 0x7f, 0xff),
        },
        ColorPalette::C64 => match named {
          NamedColor::Black => RGB::new(0x00, 0x00, 0x00),
          NamedColor::White => RGB::new(0xff, 0xff, 0xff),
          NamedColor::Gray => RGB::new(0x6C, 0x6C, 0x6C),
          NamedColor::DarkGray => RGB::new(0x44, 0x44, 0x44),
          NamedColor::LightGray => RGB::new(0x95, 0x95, 0x95),
          NamedColor::Red => RGB::new(0x68, 0x37, 0x2B),
          NamedColor::DarkRed => RGB::new(0x3f, 0x1e, 0x17),
          NamedColor::LightRed => RGB::new(0x9A, 0x67, 0x59),
          NamedColor::Brown => RGB::new(0x43, 0x39, 0x00),
          NamedColor::DarkBrown => RGB::new(0x22, 0x1c, 0x02),
          NamedColor::LightBrown => RGB::new(0x6d, 0x5c, 0x0d),
          NamedColor::Orange => RGB::new(0x6F, 0x4F, 0x25),
          NamedColor::Yellow => RGB::new(0xB8, 0xC7, 0x6F),
          NamedColor::Green => RGB::new(0x58, 0x8D, 0x43),
          NamedColor::DarkGreen => RGB::new(0x34, 0x51, 0x29),
          NamedColor::LightGreen => RGB::new(0x9A, 0xD2, 0x84),
          NamedColor::Blue => RGB::new(0x6C, 0x5E, 0xB5),
          NamedColor::LightBlue => RGB::new(0x70, 0xA4, 0xB2),
          NamedColor::DarkBlue => RGB::new(0x35, 0x28, 0x79),
          NamedColor::Purple => RGB::new(0x6F, 0x3D, 0x86),
          NamedColor::Pink => RGB::new(0xb0, 0x44, 0xac),
        },
        ColorPalette::Whitingjp => match named {
          NamedColor::Black => RGB::new(0x20, 0x25, 0x27),
          NamedColor::White => RGB::new(0xef, 0xf8, 0xfd),
          NamedColor::Gray => RGB::new(0x7b, 0x76, 0x80),
          NamedColor::DarkGray => RGB::new(0x3c, 0x3b, 0x44),
          NamedColor::LightGray => RGB::new(0xbe, 0xd0, 0xd7),
          NamedColor::Red => RGB::new(0xbd, 0x19, 0x4b),
          NamedColor::DarkRed => RGB::new(0x6b, 0x13, 0x34),
          NamedColor::LightRed => RGB::new(0xef, 0x23, 0x58),
          NamedColor::Brown => RGB::new(0xb5, 0x2e, 0x1c),
          NamedColor::DarkBrown => RGB::new(0x68, 0x1c, 0x12),
          NamedColor::LightBrown => RGB::new(0xe8, 0x7b, 0x45),
          NamedColor::Orange => RGB::new(0xff, 0x8c, 0x10),
          NamedColor::Yellow => RGB::new(0xfb, 0xd5, 0x24),
          NamedColor::Green => RGB::new(0x36, 0xbc, 0x3c),
          NamedColor::DarkGreen => RGB::new(0x31, 0x76, 0x10),
          NamedColor::LightGreen => RGB::new(0x8c, 0xe0, 0x62),
          NamedColor::Blue => RGB::new(0x3f, 0x62, 0xc6),
          NamedColor::LightBlue => RGB::new(0x57, 0xbb, 0xe0),
          NamedColor::DarkBlue => RGB::new(0x2c, 0x2f, 0xa0),
          NamedColor::Purple => RGB::new(0x70, 0x37, 0xd9),
          NamedColor::Pink => RGB::new(0xec, 0x2b, 0x8f),
        },
      };
      from_hex(hex)
    }
  }
}
